using MySql.Data.MySqlClient;
using System;
using System.Data;
using System.Windows;
using System.Windows.Controls;

namespace RestaurantWorkApp
{
    public partial class RuleControl : UserControl
    {
        // Убедитесь, что строка подключения верна
        private string connectionString = "server=localhost;port=3306;username=root;password=root;database=restaurant_db";

        public RuleControl()
        {
            InitializeComponent();
            Loaded += RuleControl_Loaded;
        }

        private void RuleControl_Loaded(object sender, RoutedEventArgs e)
        {
            LoadData();

            if (!AccessControl.CanDoOperation("Rule"))
            {
                btnAdd.IsEnabled = false;
                btnDelete.IsEnabled = false;
                dgRoles.IsReadOnly = true;
                dgRoles.CanUserAddRows = false;
                dgRoles.CanUserDeleteRows = false;
                txtName_R.IsEnabled = false;
            }
        }

        private void btnAdd_Click(object sender, RoutedEventArgs e)
        {
            if (!AccessControl.CanDoOperation("Rule"))
            {
                MessageBox.Show("У вас нет прав для добавления роли!", "Доступ запрещён",
                    MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            string ruleName = txtName_R.Text.Trim();

            if (string.IsNullOrEmpty(ruleName))
            {
                MessageBox.Show("Введите название роли");
                return;
            }

            try
            {
                using (MySqlConnection connection = new MySqlConnection(connectionString))
                {
                    // ИСПРАВЛЕНО: убраны пробелы в именах параметров
                    string query = "INSERT INTO Rule (Name_R) VALUES (@name)";
                    MySqlCommand command = new MySqlCommand(query, connection);

                    // ВАЖНО: "@name" без пробела в конце
                    command.Parameters.AddWithValue("@name", ruleName);

                    connection.Open();
                    command.ExecuteNonQuery();

                    txtName_R.Clear();
                    LoadData();
                    MessageBox.Show("Роль добавлена успешно!");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Ошибка при добавлении роли: {ex.Message}");
            }
        }

        private void btnRefresh_Click(object sender, RoutedEventArgs e)
        {
            LoadData();
        }

        private void dgRoles_CellEditEnding(object sender, DataGridCellEditEndingEventArgs e)
        {
            if (!AccessControl.CanDoOperation("Rule"))
            {
                MessageBox.Show("У вас нет прав для редактирования роли!", "Доступ запрещён",
                    MessageBoxButton.OK, MessageBoxImage.Warning);
                e.Cancel = true;
                return;
            }

            if (e.EditAction == DataGridEditAction.Commit)
            {
                DataGrid grid = sender as DataGrid;
                if (grid != null)
                {
                    DataRowView rowView = e.Row.Item as DataRowView;
                    if (rowView != null)
                    {
                        // Проверка заголовка колонки. Убедитесь, что заголовок в XAML или AutoGeneratedColumns 
                        // действительно содержит пробел, если вы его там оставили. 
                        // Лучше использовать имена колонок без пробелов.
                        if (e.Column != null && e.Column.Header.ToString() == "Название роли")
                        {
                            string newRuleName = null;

                            if (e.EditingElement is TextBox textBox)
                            {
                                newRuleName = textBox.Text.Trim();
                            }

                            if (string.IsNullOrEmpty(newRuleName))
                            {
                                MessageBox.Show("Название роли не может быть пустым");
                                e.Cancel = true;
                                return;
                            }

                            // ИСПРАВЛЕНО: ключ доступа к DataRow должен быть точным именем колонки из БД
                            // Обычно это "id_Rule", без пробела. Проверьте dataTable.Columns[0].ColumnName в отладке.
                            if (rowView["id_Rule"] != DBNull.Value)
                            {
                                int ruleId = Convert.ToInt32(rowView["id_Rule"]);
                                UpdateRoleInDatabase(ruleId, newRuleName);
                            }
                        }
                    }
                }
            }
        }

        private void UpdateRoleInDatabase(int ruleId, string newRuleName)
        {
            try
            {
                using (MySqlConnection connection = new MySqlConnection(connectionString))
                {
                    // ИСПРАВЛЕНО: убраны пробелы в параметрах
                    string query = "UPDATE Rule SET Name_R = @name WHERE id_Rule = @id";
                    MySqlCommand command = new MySqlCommand(query, connection);

                    command.Parameters.AddWithValue("@name", newRuleName);
                    command.Parameters.AddWithValue("@id", ruleId);

                    connection.Open();
                    int rowsAffected = command.ExecuteNonQuery();

                    if (rowsAffected == 0)
                    {
                        MessageBox.Show("Роль не найдена");
                        LoadData(); // Перезагрузить, чтобы синхронизировать UI
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Ошибка при обновлении роли: {ex.Message}");
                LoadData();
            }
        }

        private void btnDelete_Click(object sender, RoutedEventArgs e)
        {
            if (!AccessControl.CanDoOperation("Rule"))
            {
                MessageBox.Show("У вас нет прав для удаления роли!", "Доступ запрещён",
                    MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            if (dgRoles.SelectedItem == null)
            {
                MessageBox.Show("Выберите роль для удаления");
                return;
            }

            DataRowView selectedRow = dgRoles.SelectedItem as DataRowView;

            // ИСПРАВЛЕНО: доступ к колонке без лишнего пробела
            if (selectedRow["id_Rule"] == DBNull.Value) return;
            int id_rule = Convert.ToInt32(selectedRow["id_Rule"]);

            // ИСПРАВЛЕНО: доступ к колонке Name_R без лишнего пробела
            string roleName = selectedRow["Name_R"]?.ToString() ?? "Неизвестно";

            var result = MessageBox.Show($"Вы уверены, что хотите удалить роль '{roleName}'?",
                                        "Подтверждение удаления",
                                       MessageBoxButton.YesNo,
                                       MessageBoxImage.Question);

            if (result == MessageBoxResult.Yes)
            {
                try
                {
                    using (MySqlConnection connection = new MySqlConnection(connectionString))
                    {
                        connection.Open();
                        using (var transaction = connection.BeginTransaction())
                        {
                            try
                            {
                                // ИСПРАВЛЕНО: параметр @id без пробела
                                string deleteQuery = "DELETE FROM Rule WHERE id_Rule = @id";
                                MySqlCommand deleteCmd = new MySqlCommand(deleteQuery, connection, transaction);
                                deleteCmd.Parameters.AddWithValue("@id", id_rule);

                                int rowsAffected = deleteCmd.ExecuteNonQuery();

                                if (rowsAffected > 0)
                                {
                                    // Опционально: сброс AUTO_INCREMENT. 
                                    // Внимание: ALTER TABLE обычно нельзя выполнять внутри транзакции в некоторых версиях MySQL/MariaDB 
                                    // или это вызывает implicit commit. Если возникает ошибка здесь, уберите блок ALTER TABLE.
                                    try
                                    {
                                        string getMaxIdQuery = "SELECT MAX(id_Rule) as max_id FROM Rule";
                                        MySqlCommand getMaxIdCmd = new MySqlCommand(getMaxIdQuery, connection, transaction);
                                        object maxIdResult = getMaxIdCmd.ExecuteScalar();

                                        int newAutoIncrementValue = 1;
                                        if (maxIdResult != null && maxIdResult != DBNull.Value)
                                        {
                                            newAutoIncrementValue = Convert.ToInt32(maxIdResult) + 1;
                                        }

                                        // ALTER TABLE часто вызывает фиксацию транзакции автоматически. 
                                        // Если это критично, лучше выполнять этот запрос отдельно вне транзакции удаления.
                                        string alterQuery = "ALTER TABLE Rule AUTO_INCREMENT = @val";
                                        MySqlCommand alterCmd = new MySqlCommand(alterQuery, connection, transaction);
                                        alterCmd.Parameters.AddWithValue("@val", newAutoIncrementValue);
                                        alterCmd.ExecuteNonQuery();
                                    }
                                    catch (Exception alterEx)
                                    {
                                        // Игнорируем ошибку сброса инкремента, если она не критична, или логируем
                                        System.Diagnostics.Debug.WriteLine($"Warning: Could not reset auto increment: {alterEx.Message}");
                                    }

                                    transaction.Commit();
                                    LoadData();
                                    MessageBox.Show("Роль удалена успешно!");
                                }
                                else
                                {
                                    transaction.Rollback();
                                    MessageBox.Show("Ошибка: Роль не найдена или не была удалена.");
                                }
                            }
                            catch (Exception ex)
                            {
                                transaction.Rollback();
                                throw;
                            }
                        }   
                    }
                }
                catch (Exception ex)
                {
                    MessageBox.Show($"Ошибка при удалении роли: {ex.Message}");
                }
            }
        }

        private void LoadData()
        {
            try
            {
                using (MySqlConnection connection = new MySqlConnection(connectionString))
                {
                    string query = "SELECT * FROM Rule ORDER BY id_Rule";
                    MySqlCommand command = new MySqlCommand(query, connection);

                    connection.Open();

                    MySqlDataAdapter adapter = new MySqlDataAdapter(command);
                    DataTable dataTable = new DataTable();
                    adapter.Fill(dataTable);

                    dgRoles.ItemsSource = dataTable.DefaultView;
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Ошибка при загрузке данных: {ex.Message}");
            }
        }
    }
}